source ~path.etc: vhost
data @: config/vhost
translate:
  virtualhost-conf ~path.var: virtualhost.conf
  virtualhost-ssl-redirect-conf ~path.var: virtualhost-ssl-redirect.conf
  user-ini ~path.assets: .user.ini
  htaccess ~path.assets: .htaccess