auth:
  jwt-key: "b44224f8-8eb2-11ea-bc55-0242ac130013"
  autologin:
    cookie: "autologin"
    timeout: "+ 30 days"
mail:
  template ~path.root: /dev/src/resources/mail-template/
  sender:
    email: robotmajom@gamer365.hu
    name: Robotmajom
sites:
  - demo.test