# - Your Cli commands
/sys.missions.cli.modules:
  Application\CliCommand\Test:
  Application\CliCommand\CreateAdminUser:

# - add these keys with values to the config.local.yml
/sys.module.configs.db.databases.default:
/sys.module.configs.attachment-repository.ghost.thumbnail.secret:
/sys.module.configs.alert.bot.id:
/sys.module.configs.alert.bot.channel:
/sys.domain:
