#module.aliases

auth: Andesite\Zuul\Auth\Auth
codex: Andesite\Codex
ghosts: Andesite\Ghost\GhostManager
db: Andesite\DBAccess\ConnectionFactory
role-manager: Andesite\Zuul\RoleManager\RoleManager
twig-responder: Andesite\TwigResponder\TwigResponder
attachment-repository: Andesite\Attachment\AttachmentRepository
reroute-mission: Andesite\Mission\Reroute\RerouteMission